name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
           activate-environment: ekw-promotion
           environment-file: environment.yml
           auto-activate-base: false
           
    - name: install latex dependencies
      run: |
        sudo apt-get update
        sudo apt-get install texlive texlive-science texlive-latex-extra texlive-bibtex-extra texlive-fonts-extra texlive-lang-german biber
        sudo snap install pdftk
        sudo texhash
        
    - name: compile latex
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        git submodule init
        git submodule update
        run-content -sp
        pytest
